### ISSUE TITLE
on_privmsg not working

### ISSUE THREAD

**Issue by nikolindima** [Pytwitcher/pytwitcherapi#20]
on_privmsg method not working. Can't receive private messages.

I use

class IRCClient(pytwitcherapi.IRCClient):
    def on_privmsg(self, connection, event):
        super(IRCClient, self).on_privmsg(connection, event)
        message = self.messages.get()
        log.info('%s:%s: %s' % (self.channel, message.source.nickname, message.text))

but in docs for private messages super(IRCClient, self).**on_pubmsg**(connection, event) 
class IRCClient(pytwitcherapi.IRCClient):
    def on_privmsg(self, connection, event):
        super(IRCClient, self).on_pubmsg(connection, event)
        message = self.messages.get()
        log.info('%s:%s: %s' % (self.channel, message.source.nickname, message.text))

not working too

**Comment by storax** [comment]
Hi what is your expected behaviour and what behaviour do you examine?
Could you show post the debug logs maybe?
It's been a while but apparently if you send a PRIVMSG command where the target is not a user but the channel, the client will convert it to a pubmsg command (same for notice).

**Comment by nikolindima** [comment]
I hope that on_privmsg will work like on_pubmsg, but with private messages. When i get private message i hope on_privmsg will triggered

**Comment by storax** [comment]
Could you send an example log with debug log level please?

**Comment by nikolindima** [comment]
Here is DEBUG log. at the end i send private message to myself from browser. but def on_privmsg(self, connection, event) - not triggered
[debug.txt](https://github.com/Pytwitcher/pytwitcherapi/files/2026337/debug.txt)

**Comment by storax** [comment]
From the logs it looks like a whisper, not a privmsg. You see it in `DEBUG:irc.client:command: whisper`
Just implement on_whisper:
```
def on_whisper(self, connection,event):
    self.store_message(connection,event)
    message = self.messages.get()
    .....
```
I hope that helps. Let me know if it works. I tested that yesterday and it worked fine.

**Comment by nikolindima** [comment]
It works. Thank yo so much
